name = sidebar
description = layout demonstrating mobile first and Susy.

template = sidebar-layout

; Regions


regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
; Stylesheets
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.css
stylesheets[all][] = css/layouts/sidebar/sidebar.layout.no-query.css